package ui.tab.tabkind

object FileExtensions {
    val textFileExts: Set<String> = setOf(
        "xml",
        "txt",
        "smali",
        "java",
        "json",
        "md",
        "il",
        "properties",
        "c",
        "cpp",
        "h",
        "hpp",
        "cs",
        "js",
        "html",
        "htm",
        "css",
        "php",
        "py",
        "sh",
        "bat",
        "cmd",
        "ps1",
        "psm1",
        "psd1",
        "ps1xml",
        "psc1",
        "pssc",
        "xaml",
        "xsd",
        "xsl",
        "xslt",
        "dtd",
        "kml",
        "wsdl",
        "config",
        "conf",
        "ini",
        "inf",
        "json",
        "yml",
        "yaml",
        "toml",
        "csv",
        "kt",
        "kts",
        "gradle",
        "groovy",
        "rb",
    )


    val peFileExts: Set<String> = setOf(
        "acm",
        "ax",
        "cpl",
        "dll",
        "drv",
        "efi",
        "exe",
        "mui",
        "ocx",
        "scr",
        "sys",
        "tsp",
    )
}